### ISSUE TITLE
Visio not correctly generated

### ISSUE THREAD

**Issue by Power-Maverick** [LinkeD365/FlowToVisio#12]
All the steps came out with the following screenshot and no details:

![image](https://user-images.githubusercontent.com/36135520/106186228-fc7a3c00-6171-11eb-9cc2-dad98846abbf.png)

![image](https://user-images.githubusercontent.com/36135520/106186421-4105d780-6172-11eb-8261-a6c2f6e74ac2.png)

---
- Deployment: Online
- DB Version: 9.1.0.26146
- Connection Controls Version: 1.2020.10.35
- XrmToolBox Version: 1.2020.11.42
- Tool Version: 1.2021.1.3

**Comment by LinkeD365** [comment]
Hey Danish

Can you send a screen shot of the flow? DM if you want
