### ISSUE TITLE
Incomplete Viso File

### ISSUE THREAD

**Issue by Sebeftw** [LinkeD365/FlowToVisio#13]
Hi,

I love your tool. 
I noticed that the Visio File doesn't work with Scopes. It only shows the scope, not what happens inside the Scope.
Same with Conditions in Conditions. 

Example: I've got a Condition with a Switch inside. And it shows a Compose and a Update record. The next steps would be a Get record and a condition but thats not shown.

Happens on multiple flows with that kind of setup.

If you need more Screenshots or info I will provide you everything I can.

**Comment by LinkeD365** [comment]
Hey @Sebeftw

Thanks for raising, though I thought I did scopes

I probably need some screenshots. I created a pretty complex (in my view) test one with the scope with the condition inside which had a condition, which had a switch which had a create record, all rendered correctly. I only put top and tail scopes in, and same with conditions, where you see the condition then everything ties back to the end condition.

Could also do a screen share if that is easier

This is s/shot of the flow
![image](https://user-images.githubusercontent.com/43988771/106357774-1d709780-6300-11eb-8d96-12b3123b9165.png)

this is s/shot of visio
![image](https://user-images.githubusercontent.com/43988771/106357759-05991380-6300-11eb-86a2-b672facd00d8.png)

**Comment by Sebeftw** [comment]
Hi @LinkeD365 ,
I'll make some screenshots right now. But I can also screenshare. Just tell me how to reach you. :)

Best,
Sebe

**Comment by Sebeftw** [comment]
![flowv1](https://user-images.githubusercontent.com/68035090/106359075-7ba57680-6310-11eb-8759-3b4f678b1961.JPG)
![Flowv2](https://user-images.githubusercontent.com/68035090/106359076-7c3e0d00-6310-11eb-83f3-eef756c5616e.JPG)

In this example it's the default stream at the right side. But I've more examples.

**Comment by LinkeD365** [comment]
Reproduced it, now I have to fix it ;)

**Comment by LinkeD365** [comment]
@Sebeftw can you try with new version? 2021.1.4?

**Comment by Sebeftw** [comment]
@LinkeD365 Awesome. It works! I haven't tested all flows that were missing Parts, but the big one works! That is so cool. 

Since I don't know how your tool works this might be a stupid question: Is it possible to make the "body" which is a picture ( at least I'm not able to edit it) right now into text in a future feature? Sometimes these can get quite long and to cut them down into the main information would be cool. Or am I just don't getting how to edit these? 

Thanks again for this huge fix!
