### ISSUE TITLE
Multi-select for Create Visio

### ISSUE THREAD

**Issue by MichaelLaMontagne** [LinkeD365/FlowToVisio#15]
Unable to run Create Visio for multiple selected flows. Clicking the top corner highlights all the flows but only creates the Visio for the last item in the list. Ctrl Click or Shift Click highlights multiple flows, but only exports the last item in the selection.
![image](https://user-images.githubusercontent.com/37764843/106399952-e3bf8f80-63d8-11eb-804a-07ea84e9656a.png)

**Comment by LinkeD365** [comment]
Hhhmm, never thought of this, definetly an enhancement.  
  
1 visio file with tabs for each flow?

**Comment by MichaelLaMontagne** [comment]
1 visio file with tabs would be great!

**Comment by Sipheren** [comment]
Hi, I have just started using this and was looking to do just this, my only request or suggestion would be to allow them to export to individual Visio files as well as one large, tabbed one.

Cheers
