### ISSUE TITLE
Unable to connect to Power Automate

### ISSUE THREAD

**Issue by Danielx64** [LinkeD365/FlowToVisio#18]
Hi,

Don't know if this is the right place for support but I am stuck trying to connect to my Power Automate environment.

After filling in the box with my Application (client) ID, Directory (tenant) ID and environment id (and that happens to be the same as my Directory (tenant) ID but with the word, DEFAULT added).

I'm getting a status of Unauthorized.

Can you please give me some pointers on where I may be going wrong? 

Thank you in advanced :)

**Comment by Danielx64** [comment]
![image](https://user-images.githubusercontent.com/289220/109378480-0638c000-7927-11eb-8787-1b76b886c91d.png)

**Comment by LinkeD365** [comment]
You are certainly in the right place @Danielx64 It may be worth doing a screen share to check your configuration  
  
Can you contact me via [Contact – LinkeD365 Home](https://linked365.blog/contact/) and I will set up a teams meeting?

**Comment by Danielx64** [comment]
Hi there,

When I posted this I was just about to head to bed, now it midday here in Australia and I just tried again and now I am getting a list of the flows that I have created. Could just be a timing bug?

Cheers
