### ISSUE TITLE
Issue Retrieving Flows in Flow Visio Builder

### ISSUE THREAD

**Issue by nooriean** [LinkeD365/FlowToVisio#25]
[Write your comment/feedback/issue here]
Hi Team,

I cannot retrieve my flows in the flow Visio builder.  When I click on Connect to Dataverse, it doesn't retrieve anything.

Please help!
---
- Deployment: Online
- DB Version: 9.2.21051.136
- Connection Controls Version: 1.2021.5.42
- XrmToolBox Version: 1.2021.5.47
- Tool Version: 1.2021.5.3

**Comment by nooriean** [comment]
And when I try to enter my flow name in the search box, I receive unhandled exception error.

**Comment by LinkeD365** [comment]
Hey @nooriean can you screenshot the display of your flow and what you are seeing in the XrmToolBox? There are 2 methods to retrieve flows, and it depends whether they are in a solution or not which one you use.

**Comment by nooriean** [comment]
Hi LinkeD365,
Thank you for your prompt response. I was able to progress further but my flows are still not showing in the XRM tool.

I have attached snapshots of my flows and the XRM tool where I am stuck. 

Thanks

Ali

![flow snapshot](https://user-images.githubusercontent.com/84830111/119643527-2f51e980-be5f-11eb-9549-176e5e7266a7.jpg)
![xrm shapshot](https://user-images.githubusercontent.com/84830111/119643556-3842bb00-be5f-11eb-9a87-590de12c83c1.jpg)

**Comment by nooriean** [comment]
![XRM Snapshot2](https://user-images.githubusercontent.com/84830111/119643951-b56e3000-be5f-11eb-8447-f7014051f8eb.JPG)

I am not sure if I need to use configure to API but I am unaware of the blank areas in the snapshot.

**Comment by LinkeD365** [comment]
Hi @nooriean You do need to connect via the Flow API, steps are [here](https://github.com/LinkeD365/FlowToVisio#connecting-to-non-solutioned-flows)

**Comment by nooriean** [comment]
Thank you so much. Can you also please assist me how to connect to dataverse as for my other account, I don't get to the API screen and I only see connect to dataverse option but when I click on it, nothing happens. There also my flows are cloud based.

**Comment by nooriean** [comment]
Hi LinkeD365,

What should I use for the Select and Label fields in the above screenshot? I can get the rest but these 2 are still unknown. Can you please assist?

**Comment by nooriean** [comment]
Hi buddy, please close this ticket as I migrated my flows to Solution and then connected via dataverse to retrieve them. It was easy. I thank you for all your support!

**Comment by mucor2** [comment]
I am also seeing that prompt for Selection and Label fields, I am not using solutions at this point.  Thanks, your tool is the only one I have found to document my PAD flows for Auditor purposes. MS does not see this as a significant need.

**Comment by LinkeD365** [comment]
HI both, the selection and label are part of the ability to create one or more connections, I will create a video to show it's use. Sorry for the confusion
