### ISSUE TITLE
Suggestion - Detail Full Settings

### ISSUE THREAD

**Issue by mrhyde1st** [LinkeD365/FlowToVisio#31]
Is there a way to:

- Have the details of the actions in a step detail the full settings, and not default to using ellipses?
- Add the settings of the step as shape data e.g. the Secure Inputs/Outputs, concurrency control, timeout and repeat settings?

**Comment by LinkeD365** [comment]
Hey @mrhyde1st

The Elipises should disappear if you drag the individual steps, it does contain the detail, but displaying it all would make the flow horrible to navigate etc. I can see if I can toggle that on/off

Yes, these extra step setting needs to be added, will implement.

Thanks!

**Comment by mrhyde1st** [comment]
Yes thanks I expanded it down and saw it all, though  Is there any way to reduce the bottom margin?  When expanding there was a huge chunk of white space below the information for the steps.
