### ISSUE TITLE
Flow API connection dialog bugs

### ISSUE THREAD

**Issue by rappen** [LinkeD365/FlowToVisio#5]
Tab order is a bit funky.
Labels could align better.
And buttons.

![image](https://user-images.githubusercontent.com/2572253/95986989-1c862980-0e27-11eb-8f93-a3a432006823.png)

---
- Deployment: Online
- DB Version: 9.1.0.23470
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.10.41
- Tool Version: 1.2020.10.6

**Comment by LinkeD365** [comment]
Perfectionist! (Thanks)

**Comment by LinkeD365** [comment]
Should be aligned now.
