### ISSUE TITLE
Connect to Flow API

### ISSUE THREAD

**Issue by MichaelLaMontagne** [LinkeD365/FlowToVisio#8]
When not using CDS and connecting to Flow API using a registered app after login there is a 401 unauthorized error:
![image](https://user-images.githubusercontent.com/37764843/99601659-1272c000-29bd-11eb-9f4b-6a26e2b1a12b.png)
Azure AD shows an error id 16000:
![image](https://user-images.githubusercontent.com/37764843/99601711-31715200-29bd-11eb-8c43-3bd40edfc285.png)

**Comment by LinkeD365** [comment]
Hi @MichaelLaMontagne Thanks for the feedback, Hhhmm, will dig into this.

**Comment by LinkeD365** [comment]
@MichaelLaMontagne do you get the large pop up box to add your credentials? It looks like multi-factor auth is not on this account, is that the case?

**Comment by MichaelLaMontagne** [comment]
MFA is not enabled on that account, and the modern auth pop up box does show to add credentials.

**Comment by LinkeD365** [comment]
THis is the issue I have just replicated with another user. I would assume you are not connecting to a Dataverse environment first?

I can repro now, so working on a fix. THanks for your patience

**Comment by LinkeD365** [comment]
Hey @MichaelLaMontagne 

THink I have got the config wrong. Can you make the redirect URL (http://localhost) to a **Desktop** redirect rather than the web one I stipulate in the instructions on the blog. 

I have tested this and works with the current version.

Let me know

**Comment by MichaelLaMontagne** [comment]
Success!
